@url = http://localhost
@port = 4000
@jwt_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJfbmFtZSI6Im1hbXVuIiwiZW1haWwiOiJtYW11bkBnbWFpbC5jb20iLCJpc19zaG9wX293bmVyIjpmYWxzZX0.7TNqEEgyNkDOkHzV_HDq8fzdd8zqrY_ZPi6SMvZnj_I

GET {{url}}:{{port}}/products?limit=10&page=3
Content-Type: application/json

###
GET {{url}}:{{port}}/products/1
Content-Type: application/json

###

POST  {{url}}:{{port}}/products
Content-Type: application/json
Authorization:Bearer {{jwt_token}}

{
    "title":"iMac",
    "description":"this is the latest walton phone on 2025",
    "price":1300,
    "img_url":"wal.jpg"
}

###
PATCH  {{url}}:{{port}}/products/1
Content-Type: application/json
Authorization:Bearer {{jwt_token}}

{
    "title":"Macbook Air",
    "description":"this is mackbook air",
    "price": 656,
    "img_url":"test"
}
###

###
DELETE  {{url}}:{{port}}/products/3
Content-Type: application/json

# start user routes ______________________________________________________________________________
###
POST {{url}}:{{port}}/users
Content-Type: application/json

{
    "user_name":"mamun",
    "email": "mamun@gmail.com",
    "password": "123456",
    "is_shop_owner": false
}

###
GET {{url}}:{{port}}/users?page=1

###
POST {{url}}:{{port}}/users/login
Content-Type: application/json

{
    "email":"mamun@gmail.com",
    "password":"123456"
}

###