
GET http://localhost:4000/products
Content-Type: application/json

###
GET http://localhost:4000/products/1
Content-Type: application/json

###

POST  http://localhost:4000/products
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJfbmFtZSI6Im1hbXVuIiwiZW1haWwiOiJtYW11bkBnbWFpbC5jb20iLCJpc19zaG9wX293bmVyIjpmYWxzZX0.7TNqEEgyNkDOkHzV_HDq8fzdd8zqrY_ZPi6SMvZnj_I

{
    "title":"Samsung S25",
    "description":"this is the latest samsung phone on 2025",
    "price":1300,
    "img_url":"s25.jpg"
}

###
PATCH  http://localhost:4000/products/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJfbmFtZSI6Imhhc2liIiwiZW1haWwiOiJoYXNpYkBnbWFpbC5jb20iLCJpc19zaG9wX293bmVyIjpmYWxzZX0.Kdj3bfa59g5ge8P7V3pFGctS3FqlIf6r9S4RrrDClWA

{
    "title":"Macbook Air",
    "description":"this is mackbook air",
    "price": 656,
    "img_url":"test"
}
###

###
DELETE  http://localhost:4000/products/3
Content-Type: application/json

###

GET  http://localhost:4000/test

# start user routes
### 
POST http://localhost:4000/users
Content-Type: application/json

{
    "user_name":"mamun",
    "email": "mamun@gmail.com",
    "password": "123456",
    "is_shop_owner": false
}

###
GET http://localhost:4000/users

###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email":"mamun@gmail.com",
    "password":"123456"
}

###